
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
    "python3.11 -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "LD_LIBRARY_PATH=/nix/store/$(ls /nix/store | grep -m1 'gcc.*lib$')/lib:$LD_LIBRARY_PATH /opt/venv/bin/gunicorn -w 4 --bind 0.0.0.0:$PORT app:app"
